grid_map_topic: /grid_map_occlusion_inpainting/all_grid_map
grid_map_visualizations:
  - name: occ_points
    type: point_cloud
    params:
     layer: occ_grid_map
  - name: rec_points
    type: point_cloud
    params:
     layer: rec_grid_map
  - name: comp_points
    type: point_cloud
    params:
     layer: comp_grid_map
  - name: occ_occupancy_grid
    type: occupancy_grid
    params:
     layer: occ_grid_map
     data_min: -10
     data_max: 15
  - name: rec_occupancy_grid
    type: occupancy_grid
    params:
     layer: rec_grid_map
     data_min: -10
     data_max: 15
  - name: comp_occupancy_grid
    type: occupancy_grid
    params:
     layer: comp_grid_map
     data_min: -10
     data_max: 15